name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  timezone: ^0.5.4
  spa: ^1.1.0
  shared_preferences: any
  flutter_bloc: any
  rx_command: 4.0.0
  rx_widgets: any
  get_it: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
  assets:
    - ../assets/preloaded_data/translationsMap.json
